name: Remote Backup Workflow

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for Server 1
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATEKEY }}

      - name: Add SSH keyscan for Server 1
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Create backup directory on Server 1
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "rsync -av ${{ secrets.FILEPATH }} ${{ secrets.BACKUPPATH }}api-${{ github.run_number }}/"

      - name: Remove previous backup (old build number)
        run: |
          # SSH into the server and remove the previous backup folder
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            # List all backup directories, sort by creation time, and get the second-to-last one
            backups=$(ls -dt ${BACKUPPATH}api-* | tail -n +2)
            for backup in $backups; do
              echo "Removing old backup: $backup"
              rm -rf "$backup"  # Remove the old backup
            done
          EOF
