name: Remote Backup Workflow

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for Server 1
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATEKEY }}

      - name: Add SSH keyscan for Server 1
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Create backup directory on Server 1
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "rsync -av ${{ secrets.FILEPATH }} ${{ secrets.BACKUPPATH }}api-${{ github.run_number }}/"

      - name: Cleanup old build directories on Server 1
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "for backup in $(ls -d ${{ secrets.BACKUPPATH }}api-*); do build_number=$(echo $backup | sed -E "s/.*api-([0-9]+).*/\1/"); if [ -n "$build_number" ] && [ "$build_number" -lt "$current_build_number" ]; then rm -rf "$backup"; fi; done"
